/**
 * The agent-facing FRONT DOOR that `install-bridge` drops into a consuming repo.
 *
 * `install-bridge` wires the MCP bridge but, until this, installed NO routing — a
 * consuming-repo session was never told the Loombridge workflow exists, so the whole
 * verification core had no front door (dogfood finding GRL-C01: the entire mobile
 * ship/polish tail ran on the raw bridge, 0 plan/verify/doneness). This module is the
 * single source of truth for `LOOMBRIDGE.md`: it is compiled into `dist/` so the installed
 * CLI carries the template, and it is version-stamped so a re-run can detect staleness
 * and update in place WITHOUT ever clobbering a user-authored file.
 *
 * The rendered content is DETERMINISTIC (no timestamps): re-rendering the same version
 * is byte-identical, which is what makes a same-version re-install a true no-op.
 *
 * Every backticked tool / op / verb name below is real at HEAD; the reality-check test
 * (`routing-doc.test.ts`) fails the build if any name drifts out of the op registry /
 * CLI dispatch, so this routing file can never rot to point at a tool that doesn't exist.
 */

export const ROUTING_DOC_RELPATH = "LOOMBRIDGE.md";

/**
 * Content/schema version of the routing doc. BUMP this whenever the template body
 * changes so that `install-bridge` re-runs update an out-of-date file in place and
 * `doctor` can flag a stale one.
 */
export const ROUTING_DOC_VERSION = 6;

/**
 * The single copy-paste line a user can add to their CLAUDE.md / AGENTS.md. We never
 * edit those files (their file, their call) — we only suggest this line, and echo it
 * inside LOOMBRIDGE.md's header so the routing is discoverable even without the edit.
 */
export const SUGGESTED_ROUTING_LINE =
  "Read LOOMBRIDGE.md before Unity work — it routes game-build / verify / perf tasks to Loombridge tools.";

/**
 * Matches OUR marker AT THE START of the file (leading BOM/whitespace only) and captures
 * the version. Anchored on purpose: a user file that merely QUOTES the marker token in
 * prose mid-body must still read as user-authored — an unanchored match would claim their
 * file as ours and clobber it on the next version bump. Absent match ⇒ user-authored.
 */
const MARKER_RE = /^\uFEFF?\s*<!--\s*loombridge:routing-doc\s+v(\d+)\b/;

/** Parse the version from an existing LOOMBRIDGE.md, or null when it carries no Loombridge marker. */
export function parseRoutingDocVersion(content: string): number | null {
  const m = content.match(MARKER_RE);
  if (!m) return null;
  const v = Number.parseInt(m[1], 10);
  return Number.isFinite(v) ? v : null;
}

/** Optional-surface flags that condition the rendered body (default: all off). */
export interface RoutingDocOptions {
  /** True when `loombridge install-agent` has installed the commands/skills into this repo. */
  agentSurfaceEnabled?: boolean;
}

/**
 * Render the canonical LOOMBRIDGE.md for a given version (default: current). Deterministic
 * for a given (version, options) pair: no timestamps, no host-specific paths — the same
 * inputs always render byte-identical (what makes a same-state re-install a no-op). The
 * agent-surface line appears ONLY when that optional surface is installed, so the default
 * (surface absent) render is unchanged from prior versions.
 */
export function renderRoutingDoc(version: number = ROUTING_DOC_VERSION, options: RoutingDocOptions = {}): string {
  // Agent-AWARE so a Codex user isn't left out: `install-agent` ships skills to BOTH
  // `.claude/skills/` and `.codex/skills/`, but only Claude auto-discovers the slash
  // commands under `.claude/commands/`. Codex can't run those as commands — so point it
  // at its own skills AND tell it the command bodies are plain prose it can open + follow.
  const agentSurfaceLine = options.agentSurfaceEnabled
    ? "\n- This repo has Loombridge's agent commands + skills installed — prefer them over hand-rolling Unity build/verify steps. **Claude Code:** the `/loombridge:*` slash commands (`.claude/commands/loombridge/`) + skills in `.claude/skills/`. **Codex / other agents:** skills in `.codex/skills/`, and the same command workflows as readable prose in `.claude/commands/loombridge/*.md` — open and follow the relevant one."
    : "";
  return `<!-- loombridge:routing-doc v${version} — GENERATED by \`loombridge install-bridge\`. Do NOT hand-edit; re-run install-bridge to update. Deleting this marker makes Loombridge treat the file as yours and stop managing it. -->

# Working on this Unity project with Loombridge

This repo has the **Loombridge** Unity bridge installed — a "Playwright for Unity" that lets an AI
agent SEE, DRIVE, and **VERIFY** the game through MCP, plus a deterministic \`loombridge\` CLI that
owns the build → verify → doneness gates and the \`.loombridge/\` contract. **Read this file before any
game-build, feel, verification, or mobile-perf work** — it routes the task to the right Loombridge
surface instead of hand-rolling raw editor pokes.

> Add this one line to your CLAUDE.md / AGENTS.md (we won't edit those files for you):
> **"${SUGGESTED_ROUTING_LINE}"**

## Route the moment → the surface

| When you are… | Reach for | Instead of |
|---|---|---|
| Checking mobile perf / about to ship | the \`loombridge_mobile_audit\` MCP tool (or \`loombridge mobile-audit\` CLI) — advisory tri / texture / audio / shadow audit over the \`unity_editor_audit_mobile_assets\` bridge op | eyeballing editor CPU/GPU ms — editor perf ≠ device perf |
| Deciding whether the game is *done* | the \`loombridge_verify\` then \`loombridge_doneness\` MCP tools (or \`loombridge verify\` / \`loombridge doneness\` CLI) against the \`.loombridge/\` contract — deterministic, contract-first | declaring "looks good" off a screenshot |
| Anchoring an existing game so it can be re-checked forever | the four-line loop: \`loombridge record\` (a HUMAN plays it) → \`loombridge verify\` (drives it, captures frames) → \`loombridge approve\` (a HUMAN freezes them) → \`loombridge verify\` (now graded). Only steps 1 and 3 need a person, and \`record\` / \`approve\` are the same doors as \`loombridge trace record\` / \`trace approve\` | inserting a \`loombridge trace replay\` step — \`verify\` already replays and writes the very report \`approve\` promotes |
| Running this project's Unity EditMode tests | \`loombridge tests run\`, which resolves the editor, runs batchmode headless, and STAMPS the results into \`.loombridge/tests/\` so \`loombridge verify\` grades them offline | running the editor's Test Runner by hand and reporting the result yourself |
| A compile / domain-reload seems stuck or broken | \`unity_editor_get_project_diagnostics\` — compile errors across ALL assemblies (incl. test asmdefs), not just the last recompile | assuming the socket died |
| Running an op that recompiles (package add/remove, script edit) | chain \`unity_editor_wait_for\` with \`{ compiling: false }\` before the next op | a fixed \`sleep\` |
| Kicking off a long player / platform build | \`unity_editor_execute_menu_item\` with a raised \`timeoutMs\` — a real build far outlasts the default | letting the default timeout abort it |
| A uGUI element paints under/over another | \`unity_scene_set_sibling_index\` — a LATER sibling paints on top | hand-editing the scene YAML |
| An approved slice has to be redone (evidence invalidated, contract changed, art redone) | \`loombridge reopen <sliceId>\`: sets it \`stale\`, CLEARS its approval artifacts, cascades to every dependent, prints the re-verify chain, records it in \`history\` | editing \`.loombridge/SLICES.json\` to \`state: "stale"\` by hand |
| The console is drowning you | \`unity_editor_console_logs\` with \`errors_only\` / a \`max_chars\` cap | scrolling raw logs |
| Scene looks wrong-lit / fogged / dark | \`unity_scene_get_render_settings\` → \`unity_scene_set_render_settings\` | patching lighting in scene YAML by hand |
| Swapping a graybox for a prefab without severing wiring | \`unity_scene_find_references_to\` (pre-flight) → \`unity_asset_replace_with_prefab\` with \`remap_references\` → \`unity_scene_validate_references\` (confirm nothing severed) | a blind replace that NULLs references |

## Honesty rules an agent MUST keep

- **Never hand-write or hand-edit \`.loombridge/\` evidence** (verdicts, captures, reports). The gates
  refuse a self-graded verdict on purpose — a green you authored is not a green.
- **A capture is not a verification.** A screenshot or a play-mode frame SHOWS the game; only
  \`loombridge verify\` / \`loombridge doneness\` CERTIFY it against the contract.
- **Harness fault ≠ game defect.** If the bridge / capture rig itself fails, that is its own tier —
  never report it as a passing game, and never as a game bug.
- **\`.loombridge/\` is the single source of truth** for this project's state, contract, design target,
  captures, and reports. Read it first; don't reinvent state beside it.

## Where things live

- \`loombridge status\` — what state the project is in, without mutating anything.
- \`loombridge plan\` → \`loombridge build\` → \`loombridge verify\` → \`loombridge doneness\` — the pipeline.
- \`loombridge tests run\` is the PRODUCER for the Unity EditMode gate. It stamps \`.loombridge/tests/\`; \`loombridge verify\` is the consumer and grades those bytes offline, so no verify run ever launches an editor to check tests.
- \`loombridge doctor\` — health-check the bridge install; it prints the exact command to fix each row.
- Full tool catalog: the \`unity_ops_list\` / \`unity_ops_describe\` MCP tools.${agentSurfaceLine}
`;
}

export type RoutingDocAction =
  | "written"
  | "updated"
  | "unchanged"
  | "refused-user-authored"
  /** A filesystem error (EROFS/EACCES/EISDIR/…) — install degrades gracefully, never aborts. */
  | "write-failed";

/**
 * INFORMATIONAL-ONLY audit trail of what the LAST install run did to LOOMBRIDGE.md.
 * Consumed by nothing: `doctor` deliberately re-derives routing health from the file on
 * disk (the honest check — metadata saying "written" proves nothing if the user has since
 * deleted or replaced the file). Kept in the install record purely so a human reading
 * LoombridgeInstall.json can see what the installer decided and why.
 */
export interface RoutingDocRecord {
  relpath: string;
  /** The version now on disk (our marker), or null when user-authored / failed. */
  version: number | null;
  action: RoutingDocAction;
  /** The errno/message when action is "write-failed". */
  error?: string;
}
